### ISSUE TITLE
Are there some CMs to instead of Wurth74930000?

### ISSUE THREAD

**Issue by Robets2020** [Dfinitski/AML-30-V2#1]
It's a little difficut to buy  Wurth74930000 for me. So,  are there some CMs to instead of Wurth74930000?
Thank you for sharing the magnetic loop.

**Comment by Dfinitski** [comment]
Hi. You can use any CM chockes with 10+ uH inductance and even DIY on small torroid.

**Comment by Robets2020** [comment]
Thank you for responding.
